// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "libs/backend/prisma/src/lib/schema.prisma",
  migrations: {
    path: "libs/backend/prisma/src/lib/migrations",
    seed: "tsx libs/backend/prisma/src/lib/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
